name: Release

on:
  push:
    branches: [master]
    paths: [ModInfo.json]
  workflow_dispatch:

permissions:
  contents: read

jobs:
  validate:
    uses: salva133/My-Workflows/.github/workflows/validate-ti-mod.yml@latest
    with:
      id_prefixes: 1898_, WarForOurWorld, Roswell
      ignore_reference_fields: federation

  release:
    needs: validate
    permissions:
      contents: write
    uses: salva133/My-Workflows/.github/workflows/release-ti-mod.yml@latest
    with:
      folder_name: ScenariosExpanded
