name: Validate

on:
  push:
    branches: [master]
  pull_request:
  workflow_dispatch:

permissions:
  contents: read

jobs:
  validate:
    uses: salva133/My-Workflows/.github/workflows/validate-ti-mod.yml@latest
